name: React Native CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build React Native App
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]
        platform: [ios, android]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Build Android app
        if: matrix.platform == 'android'
        run: |
          cd android
          ./gradlew assembleRelease
          cd .. 
